# Configure loclahost Operator and Spawn Master Node
- name: Configure the Master
  hosts: localhost
  tags: Netm4ul
  vars_files:
    - config.cfg

  vars:
    host_group: master
    count: 1

  pre_tasks:
    - block:
      - name: Local pre-tasks
        include_tasks: playbooks/local.yml
        tags: [ 'always' ]

      - name: Local pre-tasks
        include_tasks: playbooks/local_ssh.yml
        become: false
        when: Deployed_By_Netm4ul is defined and Deployed_By_Netm4ul == "Y"
        tags: [ 'local' ]
      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always

  roles:
    - { role: scaleway, tags: ['scaleway'] }

  post_tasks:

    - block:
      - name: Local post-tasks
        include_tasks: playbooks/post.yml
        become: false
        tags: [ 'cloud' ]

      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always

# Install needed
- name: Configure the server and install required software
  hosts: master
  gather_facts: false
  tags: Netm4ul
  become: true
  vars_files:
    - config.cfg

  pre_tasks:
    - block:
      - name: Common pre-tasks
        include_tasks: playbooks/common.yml
        tags: [ 'scaleway' ]
      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always

  tasks:
      - include_tasks: playbook/nodes.yml

  post_tasks:
    - block:
      - debug:
          msg:
            - "{{ congrats.common.split('\n') }}"
            - "    {% if cloud_deployment is defined %}{{ congrats.ssh_access }}{% endif %}"
        tags: always

      rescue:
        - debug: var=fail_hint
          tags: always
        - fail:
          tags: always

# Install Client Nodes
- name: Deploy client nodes
  hosts: localhost

  vars:
    host_group: nodes
    count: 2

  tasks:

    - name: Launch the servers
      include_tasks: scaleway/tasks/main.yml
      register: new_nodes
      with_sequence:
        count = {{ count }}

    - name: 2nd add host
      add_host: name={{ item.server.public_v4 }}
                groups=created_nodes
                ansible_user=root
                instance_name={{ item.server.name }}
      with_items: "{{ newnodes.results }}"

# Configure Client nodes
- name: Configure nodes
  hosts: created_nodes
  become: false
  gather_facts: false
  tasks:
    - name: "Wait for SSH banners"
      local_action: wait_for port=22 host="{{ inventory_hostname }}" search_regex=OpenSSH delay=5
      become: False

    - include_tasks: playbook/nodes.yml