---

- name: Pull project from git
  git: repo={{ repo_url }} dest={{ app_dir }} version={{ app_version }}

- name: Install Docker and Docker Compose
  block:
    - name: Download Docker
      get_url:
        url: https://get.docker.com
        dest: ~/docker.sh
        mode: 0700

    - name: Install Docker
      shell : ~/docker.sh

    - name: Get uname -s
      shell: uname -s
      register: system_uname_s

    - name: Get uname -m
      shell: uname -m
      register: system_uname_m

    - name: Download Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-"{{ item.s }}"-"{{ item.m }}" -o
        dest: /usr/local/bin/docker-compose
        mode: 0700
      with_items : { s: system_uname_s, m: system_uname_m }