---

- name: Pull project from git

  git:
    repo: 'https://github.com/netm4ul/netm4ul.git'
    dest: ~/
    clone: yes
    version: develop

- name: Install Docker and Docker Compose
  block:
    - name: Download Docker
      get_url:
        url: https://get.docker.com
        dest: ~/docker.sh
        mode: 0700

    - name: Install Docker
      shell : ~/docker.sh

    - name: Get uname -s
      raw: uname -s
      register: system_uname_s

    - name: Get uname -m
      raw: uname -m
      register: system_uname_m

    - name: Download Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-"{{ item.s.stdout }}"-"{{ item.m.stdout }}" -o
        dest: /usr/local/bin/docker-compose
        mode: 0700
      with_items : { s: system_uname_s, m: system_uname_m }